Added Jenkinsfile
EclipseFdn/git-eca-rest-api pull request #2
Opened 2020-03-10 14:42 UTC by autumnfound

Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

2020-03-10 14:47 UTC, chrisguindon commented
I think this a great starting point but the build is failing on jenkins:

`ERROR] Tests run: 16, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 19.576 s <<< FAILURE! - in org.eclipsefoundation.git.eca.helper.CommitHelperTest
[ERROR] validateCommitNoAuthorMail  Time elapsed: 0.005 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.eclipsefoundation.git.eca.helper.CommitHelperTest]: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: oauth2.client-secret
[INFO] Running org.eclipsefoundation.git.eca.resource.ValidationResourceTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s - in org.eclipsefoundation.git.eca.resource.ValidationResourceTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   CommitHelperTest.validateCommitNoAuthorMail » TestInstantiation TestInstanceFa...
[INFO] 
[ERROR] Tests run: 17, Failures: 0, Errors: 1, Skipped: 1`

2020-03-27 08:59 UTC, mbarbero requested changes

2020-03-27 08:59 UTC, mbarbero commented on src/main/k8s/production.yml
> +      volumes:
Please check https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod for how to use secret inside pod's container. You need 2 things: a volume declaration (that reference the secret itself) and a volume mount to indicate where the volume should be mounted.

2020-03-27 08:59 UTC, mbarbero commented on src/main/k8s/staging.yml
> +      volumes:
same as above

2020-03-31 14:18 UTC, chrisguindon approved these changes
Looks good to me but I want to make sure that @mbarbero is ok with this before we merge!

2020-03-31 14:20 UTC, mbarbero approved these changes

2020-03-31 14:21 UTC, merged